Cargo.toml, README.md, src/datetime.rs, src/julian.rs, src/lib.rs, tests/datetime.rs, tests/julian.rs
=> Add centuries since J2000, some constants, and re-exports

Cargo.toml, README.md, src/epoch.rs, src/lib.rs, src/sim.rs
=> More TAI/UTC tests and rand crate version bump

Cargo.toml, src/lib.rs, src/sim.rs
=> Fixed `noise_up`

Cargo.toml, src/sim.rs
=> Add a single sampler to the clock

src/sim.rs
=> Implements #62

Cargo.toml, README.md, src/epoch.rs
=> Convert to/from Gregorian representations of UTC and TAI

Cargo.toml, README.md, src/epoch.rs, src/lib.rs
Closes #69; closes #47; closes #70; closes #66; closes #67
=> Hifitime version 1.0.11

Cargo.toml, src/duration.rs, src/lib.rs, src/timeseries.rs
=> Version 2.1

src/epoch.rs
=> Include nanos in maybe_from_gregorian

Cargo.toml, src/lib.rs, src/timeseries.rs
=> Fixed bug in TimeSeries

Cargo.toml, src/duration.rs, src/epoch.rs, src/lib.rs
=> Fix Duration display and allow init from hi/lo values

Cargo.toml, README.md, src/duration.rs, src/epoch.rs
Also add GPST nanoseconds
Closes #115 
=> `to_parts` and Epoch parts constructor

.github/workflows/tests.yml, Cargo.toml, README.md, src/duration.rs, src/epoch.rs, src/lib.rs, src/timeseries.rs
=> #![no_std] support

Cargo.toml, src/duration.rs, src/epoch.rs, src/lib.rs
Closes #130 
Closes #129 
Closes #128
=> Changes pre-v.3.3.0

README.md, src/timeseries.rs
=> Fix len() and size_hint() in TimeSeries

.github/workflows/formal_verification.yml, .github/workflows/tests.yml, Cargo.toml, README.md, src/asn1der.rs, src/duration.rs, src/epoch.rs, src/lib.rs, src/timeseries.rs
Also add formal verification to creating an Epoch from its UTC elements.
Closes #139
=> Add ASN1 distinguished encoding rules encoding and decoding for Epoch and Duration

.github/workflows/benchmarks.yml, .github/workflows/formal_verification.yml, .github/workflows/tests.yml, Cargo.toml, README.md, examples/python/basic.py, src/asn1der.rs, src/duration.rs, src/epoch.rs, src/lib.rs, tests/duration.rs, tests/epoch.rs
=> Workflow improvements

.github/workflows/formal_verification.yml, .github/workflows/tests.yml, Cargo.toml, README.md, benches/bench_duration.rs, src/duration.rs, src/epoch.rs, src/lib.rs, tests/duration.rs
=> Use lexical_core for parsing durations

.github/workflows/tests.yml, Cargo.toml, README.md, src/duration.rs, src/epoch.rs, src/lib.rs, src/parser.rs, src/timescale.rs, tests/duration.rs, tests/epoch.rs
Reduces `FromStr` latency by 99%!
Updated README.
Prep for 3.5.0 release
Closes #150
=> Remove Regex in favor of lexical_core for parsing

.github/workflows/python.yml, .github/workflows/tests.yml
=> Maybe fix the PyPI release

src/timescale.rs
=> timescale.rs: derive serdes traits when feasible

src/timescale.rs, tests/timescale.rs
=> timescale: identify GNSS timescales from standard 3 letter codes

src/timeunits.rs
=> src/timeunits.rs: fix minor typo

README.md, src/errors.rs, tests/epoch.rs
This pull request fixes a few typos.
=> Fix some typos

src/month.rs
fixes https://github.com/nyx-space/hifitime/issues/234
=> fix december for MonthName from u8

Cargo.toml, src/duration/kani_verif.rs, src/duration/mod.rs, src/duration/parse.rs, src/efmt/format.rs, src/epoch/gregorian.rs, src/epoch/leap_seconds_file.rs, src/epoch/mod.rs, src/epoch/python.rs, src/epoch/system_time.rs, src/epoch/ut1.rs, src/errors.rs, src/lib.rs, src/month.rs, src/parser.rs, src/python.rs, src/timescale/mod.rs, src/timeunits.rs, src/weekday.rs, tests/efmt.rs, tests/epoch.rs, tests/python/test_duration.py, tests/python/test_epoch.py
=> Rename `EpochError` to `HifitimeError` and add exception testing

.github/workflows/python.yml, src/epoch/python.rs, src/errors.rs, tests/python/test_epoch.py
=> Add Python datetime interop

tests/polynomial.rs
* static offset (a0, 0, 0) model
* static offset + linear (a0, a1, 0) model
=> Polynomial: add two other tests

src/polynomial.rs
- Provide casts that might prove convenient to the end users
=> Polynomial: provide convenient (f64, f64, f64) casts

.github/workflows/python.yml
Fixes https://github.com/nyx-space/hifitime/issues/340
aarch64 build wheels were failing because of https://github.com/briansmith/ring/issues/1728
=> Re-enable pytest for aarch64, ppc64, armv7 and build wheels for aarch64, 
