- Cargo.toml
- README.md
- src/duration.rs
- src/epoch.rs
- src/lib.rs
- src/timeseries.rs
Leads to an 85 to 90% speed improvement.
Closes #93 
Closes #90 
Closes #95  
Closes #96
> Use TwoFloat instead of lossless fractions for time

- Cargo.toml
- src/epoch.rs
- src/lib.rs
Hi!  Thanks very much for `hifitime`, it's been a lifesaver to deal with JDs, MJDs and leap seconds.  I've been using it for about 1.5 years now.
I've got a lot going on in this PR so if you'd prefer for me to break it up or you have any questions, please let me know.  I also don't 100% trust myself with getting everything correct so I'd appreciate some experienced eyes over the changes.
The first commit is simple enough - it just specifies patch versions for dependencies seeing as that's generally a good thing to do.  In the commit message I've linked the relevant Rust users forum post that set me off tidying up this kinda stuff all over the place.
The second commit adds a bunch of functions that seemed to simply be missing from the library previously (`from_utc_{seconds,days}`, …
> New methods and a fix for the GPS epoch

- .github/workflows/tests.yml
- Cargo.toml
- README.md
- src/duration.rs
- src/epoch.rs
- src/lib.rs
Did some light refactoring and benchmarked (will be deleted before merging). What are your thoughts about this approach ?
Note : this currently relies on bigint_helper_methods (https://github.com/rust-lang/rust/issues/85532) so compiles on Nightly only
> Proposal for new approach with nanoseconds integers

- src/epoch.rs
- src/lib.rs
Thanks for all the hard work you've done on this on this project. I've been using it for astronomy tools in my lab for about a year now.
I've added conversion function to/from the unix epoch timestamp (01 Jan 1970 00:00:00 UTC).
If you'd like I could add unix_tai convenience functions too which do not remove the leap seconds.
closes #22
> Add UNIX timestamp

- Cargo.toml
- README.md
- src/duration.rs
- src/epoch.rs
- src/lib.rs
> Initialize from system time and add `ceil`, `floor`, and `round` to durations

- src/epoch.rs
Derives Ord and Eq for epoch.
I also added a small test to check expected orderings between two epochs.
> derive Ord and Eq for Epoch

- .github/workflows/formal_verification.yml
- .github/workflows/tests.yml
- Cargo.toml
- src/duration.rs
- src/epoch.rs
- src/timeseries.rs
When attempting to compile for a target: aarch64-unknown-none I was failing due to a couple reasons.
They both go back to there is no-std library reference available for that architecture.
Compiling with "no_std" on my linux target works fine.
If you attempt a build with cargo such as:
```
cargo build --no-default-features --target=aarch64-unknown-none -Z build-std=core
```
The current hifitime/master was failing.
Thought I'd pass along my current patches.
Feel free to edit, change, or disregard.
I believe this goes back to the resolver dependency as shown in:
- https://github.com/rust-num/num-traits/issues/138
Added resolver="2" to the cargo.toml to fix this.
Another option would be to upgrade to the "edition = 2021" in cargo.toml.
The 2021 edition defaults to the new resolver.
Also, in …
> Fix num-traits usage for no-std

- .github/workflows/formal_verification.yml
- examples/python/timescales.py
- src/duration.rs
- src/epoch.rs
- tests/duration.rs
- tests/epoch.rs
- tests/timeseries.rs
The biggest pain here was correctly formatting and parsing epochs before 1900 TAI because one has to count the duration within one day backward in order to correctly format it.
The tests now ensure that whatever is printed with hifitime can also be read with `from_str`.
> Fix formatting of Epochs

- .github/workflows/tests.yml
- Cargo.toml
- README.md
- examples/python/basic.py
- examples/python/timescales.py
- src/asn1der.rs
- src/deprecated.rs
- src/duration.rs
- src/epoch.rs
- src/lib.rs
- src/timescale.rs
- src/timeseries.rs
- tests/duration.rs
- tests/epoch.rs
> Methods renamed to be idiomatic

- benches/bench_epoch.rs
- src/epoch.rs
The loops that were originally there didn't optimise well. This new code optimises much better with less branches
The one regression is a false positive and on re-runs switched between + and -
> optimise gregorian

- src/duration.rs
Kani `any` is a symbolic value meaning all valid states will be solved for. See here: https://model-checking.github.io/kani/tool-comparison.html?highlight=exhau#comparison-with-other-tools
> Remove redundant tests

- .github/workflows/formal_verification.yml
- README.md
- src/duration.rs
- src/epoch.rs
- src/timeseries.rs
- src/timeunits.rs
- tests/duration.rs
- tests/epoch.rs
- tests/timeseries.rs
+ Epoch and Duration now have a `min` and `max` function which respectively returns a copy of the epoch/duration that is the smallest or the largest between `self` and `other`, cf. [#164](https://github.com/nyx-space/hifitime/issues/164).
+ [Python] Duration and Epochs now support the operators `>`, `>=`, `<`, `<=`, `==`, and `!=`. Epoch now supports `init_from_gregorian` with a time scape, like in Rust. Epochs can also be subtracted from one another using the `timedelta` function, cf. [#162](https://github.com/nyx-space/hifitime/issues/162).
+ TimeSeries can now be formatted in different time scales, cf. [#163](https://github.com/nyx-space/hifitime/issues/163)
Closes #162 
Closes #163 
Closes #164
> Usability enhancements, especially for Python

- Cargo.toml
- README.md
- benches/bench_epoch.rs
- examples/python/basic.py
- src/asn1der.rs
- src/duration.rs
- src/epoch.rs
- src/lib.rs
- src/timescale.rs
- tests/epoch.rs
GST: Galileo System time is defined as starting 13 seconds
prior midnight on August 22nd 1999
GPST: GPS System time is defined as starting on Jan 6 1980 midnight
BDT: BeiDou system time scale, defined as starting on Jan 1st 2006 midnight.
All of them do not take leap second into account.
> introducing GNSS timescales

- src/timescale.rs
- tests/timescale.rs
* implement fmt::Display for TimeScale enum
* implement special 0x format for GNSS timescales
* introduce a testbench
> timecale.rs: introduce format/display

- README.md
> readme: fix BeiDou typo

- src/duration.rs
- src/epoch.rs
- src/timescale.rs
Hash is required if we want structures like "HashMap" or "BTreeMap"
indexed by an Epoch
> epoch: derive Hash

- src/epoch.rs
- src/timescale.rs
- tests/timescale.rs
Hello @ChristopherRabotin,
I just noticed we don't have a default constructor for these, while it is correctly defined for `Duration`.
> epoch, timescale: implement default trait

- .github/workflows/formal_verification.yml
- Cargo.toml
- README.md
- src/duration.rs
- src/epoch.rs
- src/lib.rs
- src/timescale.rs
- src/timeunits.rs
- tests/duration.rs
- tests/epoch.rs
Refer to #184 for progress.
Implements #184 
List of bugs fixed thanks to Kani:
+ `normalize()` in Duration (which is called after _every_ operation on a Duration) could overflow near the maximum or minimum number of centuries when the nanoseconds were still within the MIN/MAX of the structure.
+ `normalize()` in Duration would overflow when the duration was _near_ (but below) the MAX
+ `Duration::neg()` would overflow near MIN/MAX
+ `PartialEq` on `Duration` would overflow near MIN/MAX
+ `try_truncated_nanoseconds` would overflow on any duration where the input was larger than the MAX
+ `Ops::Add` would fail when the centuries was the `i16::MIN` but the nanoseconds were still valid
+ `Ops::Add` would overflow when the right hand side input was not normalized
+ `Ops::Sub` would underflow …
> Extend formal verification

- .github/workflows/python.yml
This updates `actions/download-artifact` and `actions/upload-artifact` to their newest major version v3.
Changes in [actions/download-artifact](https://github.com/actions/download-artifact):
> ## v3.0.2
> - Bump `@actions/artifact` to v1.1.1
> - Fixed a bug in Node16 where if an HTTP download finished too quickly (<1ms, e.g. when it's mocked) we attempt to delete a temp file that has not been created yet
>
> ## v3.0.1
> - Bump @actions/core to 1.10.0
> - Update actions/core package to latest version to remove `set-output` deprecation warning
>
> ## v3.0.0
>
> - Update default runtime to node16
> - Update package-lock.json file version to 2
Changes in [actions/upload-artifact](https://github.com/actions/upload-artifact):
> ## v3.1.2
> Update all `@actions/*` NPM packages to their latest …
> Update artifact-related actions in GitHub Actions workflows to v3

- .github/workflows/benchmarks.yml
- .github/workflows/formal_verification.yml
- .github/workflows/tests.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/nyx-space/hifitime/actions/runs/4148528979:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain).
> Replace unmaintained actions-rs/toolchain actions in CI workflows

- .github/workflows/tests.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/nyx-space/hifitime/actions/runs/4148528979:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/cargo` are replaced by direct invocations of `cargo`.
> Replace unmaintained actions-rs/cargo actions in CI workflows

- src/asn1der.rs
- src/epoch.rs
- src/timescale.rs
- tests/epoch.rs
- tests/timescale.rs
Introduces QZSS time scale, which is straight forward in the sense it behaves like GPST strictly, but comes from a set of dedicated clocks.
Partial answer to issue #210
> support qzss time scale

- README.md
- src/duration.rs
- src/epoch.rs
- tests/epoch.rs
> Cleanup README and fix Gregorian print bug < 1900

- Cargo.toml
- examples/python/basic.py
- examples/python/timescales.py
- src/asn1der.rs
- src/deprecated.rs
- src/duration.rs
- src/efmt/consts.rs
- src/efmt/format.rs
- src/efmt/formatter.rs
- src/efmt/mod.rs
- src/epoch.rs
- src/errors.rs
- src/leap_seconds.rs
- src/leap_seconds_file.rs
- src/lib.rs
- src/month.rs
- src/parser.rs
- src/python.rs
- src/timescale.rs
- src/timeseries.rs
- src/timeunits.rs
- src/ut1.rs
- src/weekday.rs
- tests/python/test_epoch.py
This is was an oversight of the code and testing.
Fix #248
> Day of year formatting now parses elapsed time

- Cargo.toml
- src/epoch.rs
- src/lib.rs
- src/system_time.rs
`std::time::SystemClock::now()` does not work in the browser. The [instant](https://crates.io/crates/instant) provides an alternative that works in the browser and falls back to `std::time::SystemClock` on non-WASM targets. I have added a new `web` feature flag that enables the extra features from the `instant` crate.
This is required for running the [ANISE](https://github.com/nyx-space/anise) gui in the browser.
> Adds support for using hifitime in WASM targets

- src/efmt/format.rs
- src/efmt/formatter.rs
- src/parser.rs
- tests/efmt.rs
- tests/epoch.rs
* Support %yy year on two digits
> Introduce %y formatter

- Cargo.toml
- src/duration.rs
- src/efmt/format.rs
- src/epoch.rs
- tests/epoch.rs
The day of year computation was broken: first, it didn't work well when the time scale reference epoch was not J1900 (cf #272 ), and moreover, it started counting the days at zero, when it should have one (to meet the GPS standard and the Python behavior).
> [Maybe breaking change] Fix day of year computation

- src/duration.rs
Just a fix of what I believe is a typo, but also a couple out-of-code comments re: possible changes.
Fix: the docs said that -1 century < (-1 century + 1 ns), which I believe is the opposite of what you meant.  (Had to download library and check though since, per the point of explaining, it could've gone either way :)
A couple other things that might be worth changing/clarifying:
1. > It was decided that the nanoseconds corresponds to the nanoseconds _into_ the current century.
- I think that's *also* untrue, yes?  Nanoseconds are toward "the future" as it were.  Rather than toward any period (absolute or dynamic).  Technical correctness aside, I also found that phrasing confusing.  (But I'm not a space-related scientist, so maybe this is common phrasing in your field. ?)
2. > The …
> docs(fix): fixed reversed description of duration magnitude

- Cargo.toml
- src/system_time.rs
- tests/epoch.rs
Would fix #278 
Allows consistent usage of SystemTime between targets (including WASM).
I replaced all uses of std::time::SystemTime with web_time::SystemTime, and removed the overloaded `duration_since_unix_epoch` method for the WASM target.
I haven't vetted the web_time library for other uses, but it seems to be working fine. 
So this is just a proposal and might need more discussion/research before including as dependency.
> Draft: replace std::time:SystemTime with web_time::SystemTime

- src/epoch.rs
- src/errors.rs
Fix 11. and 12. Arithmetic overflow bug and  in #244 
Consider using saturating_sub and saturating_mul to avoid the panic.
The problem lies in https://github.com/nyx-space/hifitime/blob/822c0a0ee4da21f385bc520547431fd1b3ed7d6f/src/epoch.rs#L735
where `year_since_1900` is overflowing to i32.
https://github.com/nyx-space/hifitime/blob/822c0a0ee4da21f385bc520547431fd1b3ed7d6f/src/epoch.rs#L736
where `365 * yeaer_since_1900` is overflowing to i32.
I've opted to use `saturating_sub` and `saturating_mul`. These functions ensure that there's a maximum boundary, preventing overflow panic.
PS: As a newcomer to the Rust project, I apologize for any inconvenience this may cause.
> Fix panic caused by arithmetic overflow

- src/epoch.rs
Fix 1. Array out-of-bounds error in #244 
In the replay file, the input "94-11-05T08:15:34.0-:0" does not adhere to the Gregorian date time format, leading to prev_idx > end_idx, which, in my opinion, should trigger an error.
> Fix panic caused by array out of bounds

- src/efmt/format.rs
Fix 8.Unwrap error in #244 
In the replay file, `from_format_str` takes "%" as format_str, thus causing the format returned by `from_str` empty.
https://github.com/nyx-space/hifitime/blob/822c0a0ee4da21f385bc520547431fd1b3ed7d6f/src/efmt/format.rs#L159
This results in the items in `parse` being empty, which causes an unwrap error. In my opinion, it should be classified as an UnknownFormat error since it's related to format.
> Fix panic caused by unwrap

- .github/workflows/python.yml
- Cargo.toml
- src/duration/kani_verif.rs
- src/duration/mod.rs
- src/duration/parse.rs
- src/efmt/format.rs
- src/epoch/gregorian.rs
- src/epoch/leap_seconds_file.rs
- src/epoch/mod.rs
- src/epoch/python.rs
- src/epoch/system_time.rs
- src/epoch/ut1.rs
- src/errors.rs
- src/lib.rs
- src/month.rs
- src/parser.rs
- src/python.rs
- src/timescale/fmt.rs
- src/weekday.rs
- tests/duration.rs
- tests/efmt.rs
- tests/epoch.rs
- tests/timescale.rs
- tests/weekday.rs
This PR adds `snafu` for error handling. The error messages are more precise, provide more context than the previous ones, and specific type errors are handled in their own error structs. All error structs are marked as non-exhaustive to allow for expanding at a latter date.
I'd like to have the same errors be available from Python, but I'm waiting to hear back from https://github.com/PyO3/pyo3/discussions/4165 for implementation recommendations.
Closes #245 .
> Improve error handling

- .github/workflows/python.yml
- tests/epoch.rs
- tests/python/test_epoch.py
This was actually fixed in #303, but the regression test in Python has only been added in this PR.
This PR also fixes the MacOS CI build.
Closes #249
> Add Python regression test for #249

- src/epoch/mod.rs
- src/lib.rs
- tests/epoch.rs
Added a regression test to ensure that the printing of dates initialized from MJD is as expected. Clarified in the test that Hifitime's "prime epoch" is at midnight on 1900-01-01, so 0.5 days off of J1900. This behavior matches NAIF SPICE, which is an important property of hifitime as it is used to replace SPICE for time computations.
Renamed the following constants
- J1900_NAIF -> JD_J1900
- J2000_NAIF -> JD_J2000
- J1900_OFFSET -> MJD_J1900
- J2000_OFFSET -> MJD_J12000
Removed constants (unused):
- J2000_TO_J1900_DURATION
- JDE_OFFSET_DAYS
- JDE_OFFSET_SECONDS
Closes #282
> Breaking change: renamed Julian date constants and removed other Julian date constants

- src/epoch/gregorian.rs
- src/epoch/mod.rs
- tests/epoch.rs
Prior to this PR, there was no conversion of the time scale in `to_gregorian_str`, but it should have happened. The Gregorian printing was fixed in #303 .
Closes #288
> Fix bug in `to_gregorian_str` 

- Cargo.toml
Reverts nyx-space/hifitime#309
This is required prior to the release of anise 0.4 and Nyx 2 beta. Nyx requires pyo3 log and other stuff that have yet to be updated.
> Revert "Update pyo3 requirement from 0.21.1 to 0.22.0"

- src/epoch/mod.rs
- src/lib.rs
The doc cfg macro emphasizes in the documentation how to unlock feature dependent structures
> Introduce doc_cfg and mark ut1 within ut1 crate feature

- src/duration/mod.rs
- tests/duration.rs
Fix 14. Arithmetic overflow bug in #244  
In #244 , `ceil()` is called with a duration of 0, which can lead to an arithmetic overflow. While returning 0 is one way to address this, another approach is to report an error to the user. 
I'm not very familiar with operations involving time, so apologies for any misunderstandings.
> Fix ceil with zero duration

- src/efmt/format.rs
- tests/efmt.rs
Fix panic 2-4 in #244 and panic 16-28 in #246 
The 16 panics are all attributed to missing check of the size of `items` of `Format` in from_str().
> Fix token exceed in from_str()

- src/duration/std.rs
- tests/duration.rs
This works towards closing #337 by making the implementations of `From<std::time::Duration> for Duration` and `From<Duration> for std::time::Duration` lossless. Thank you!
> Implement lossless From methods for Duration conversions

- pyproject.toml
While developing an application in Python that uses Hifitime I moved from Python 3.12 to 3.13.
This resulted in errors at update of the dependencies:
```bash
$ poetry install --with=test,docs
Installing dependencies from lock file
Package operations: 1 install, 0 updates, 0 removals
- Installing hifitime (4.0.0): Failed
ChefBuildError
Backend subprocess exited when trying to invoke build_wheel
Running `maturin pep517 build-wheel -i /home/jazzinghen/.local/share/pyenv/versions/3.13.0/bin/python3.13 --compatibility off`
📦 Including license file "/tmp/tmp2koz9epo/hifitime-4.0.0/LICENSE.txt"
🔗 Found cffi bindings
🐍 Using CPython 3.13 at /home/jazzinghen/.local/share/pyenv/versions/3.13.0/bin/python3.13 to generate the cffi bindings
Compiling proc-macro2 v1.0.88
Compiling unicode-ident v1.0.13 …
```
> Add Python feature to Maturin configuration in pyproject.toml

- Cargo.toml
- benches/crit_duration.rs
- src/duration/mod.rs
- src/duration/parse.rs
- src/efmt/formatter.rs
- src/timeunits.rs
- src/weekday.rs
- tests/duration.rs
- tests/epoch.rs
- tests/timescale.rs
> Fix parsing of microseconds with UTF8 symbol and parsing negative durations

- .github/workflows/python.yml
- Cargo.toml
* Documentation for UT1 and feature dependent stuff does not show up
* This should fix #353
> Fix UT1 feature documentation

- tests/python/test_epoch.py
This PR fixes a bug where `datetime.UTC` caused an `AttributeError` in Python versions where `UTC` is not a class attribute. The error occurred because `UTC` is accessed via the `datetime` module (`datetime.UTC`), not the `datetime.datetime` class. Replaced `datetime.UTC` with the widely compatible `timezone.utc` to ensure cross-version compatibility (we could import `UTC` from `datetime` instead). Also fixed a small typo along the way.
> Correct UTC import in Python unit tests

- .github/workflows/formal_verification.yml
- .github/workflows/kani-builder.yml
- .github/workflows/weekly-kani-checker.yaml
- src/duration/mod.rs
- src/kani_verif.rs
In a much older version of kani, serde wouldn't compile. This seems to have been fixed. It should fix #394 .
This PR also reenables kani in the CI.
> Enable serde for kani

- Cargo.toml
- hifitime.pyi
- pyproject.toml
- src/epoch/gregorian.rs
- src/epoch/initializers.rs
- src/epoch/python.rs
> Move extension-module to maturin features

- src/epoch/gregorian.rs
- tests/epoch.rs
This will now give out a invalid georgian date : 
```
let e = Epoch::from_gregorian_tai(2024, 2, 30, 00, 00, 0,0);
println!("{e}");
```
Previously, Feb 30 and Feb 31 in an leap year were considered valid.
> Check max days in feb month during a leap year

- src/epoch/gregorian.rs
- tests/epoch.rs
Previously, one could initialize an Epoch with the 60th second on a leap day even if the selected time scale did not support leap seconds. This PR makes this an error.
Importantly, this PR also fixes an error in the `julian_epoch` test where an epoch was initialized on the leap second but ... in TAI. There is no leap second in TAI, so this initialization should fail. The test case was also expanded to confirm the computation of Modified Julian Dates using NASA HEASARC, with an extra test and a clarification that leap second management is implementation dependent.
Thanks for the report @ephraim71 !
> Non-leap time scales error on init with leap second 

- Cargo.toml
- src/duration/mod.rs
- src/timeunits.rs
The unit constructors for `Duration` (`from_nanoseconds`, `from_days`, etc.) are made `const`-compatible, allowing `Duration` to be declared as a compile-time constant. This is a fix for issue #422.
- `Duration::normalize()` uses plain `/` and `%` operators in place of `div_euclid` and `rem_euclid`.
- A const-compatible `Duration::is_equal_to(other: Duration)` is added to replace two (non-)equality checks in `Duration::normalize()`.
- `Duration::from_total_nanoseconds()` is changed to use explicit `as i128` casts instead of `into()`.
- The existing implementation of `Mul<f64> for Unit` is moved to a non-trait `const` method called `Unit::const_multiply`. This method is called by the regular `mul`, and from the unit constructors.
Additionally, for compatibility with the MSRV (1.82), the …
> Make unit constructors for `Duration` const-compatible
